openapi: "3.0.0"
info:
  version: 1.0.0
  title: Purchase payment
  description: API for Purchase payment
  contact:
    name: Stella
    email: s.b.nagirner@gmail.com
servers:
  - url: http://api.example.com/hellostella/dopayment/api

paths:
  /transaction:
    post:
      summary: Process a payment transaction
      operationId: processTransaction
      requestBody:
        description: JSON object containing payment transaction details.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - rquid
                - datetime
                - returnUrl
                - failUrl
                - merchantid
                - merchantName
                - transactionType
                - orderid
                - amount
                - quantity
                - currency
                - transactionId
                - clientIP
                - clientEmail
                - clientName
                - paymentMethods
              properties:
                rquid:
                  type: string
                  format: uuid
                  description: Request unique identifier.
                  example: "123e4567-e89b-12d3-a456-426614174000"
                datetime:
                  type: string
                  format: date-time
                  description: Timestamp of the transaction request.
                  example: "2024-09-12T14:23:45Z"
                returnUrl:
                  type: string
                  format: uri
                  description: URL where the user is redirected upon successful payment.
                  example: "https://page1.ru"
                failUrl:
                  type: string
                  format: uri
                  description: URL where the user is redirected if the payment fails.
                  example: "https://page2.error.ru"
                merchantid:
                  type: string
                  description: Unique identifier for the merchant.
                  example: "merchant123"
                merchantName:
                  type: string
                  description: Name of the merchant.
                  example: "Example Merchant"
                transactionType:
                  type: string
                  enum: [buy, refund, cancel]
                  description: Type of transaction.
                  example: "buy"
                orderid:
                  type: string
                  description: Identifier for the order.
                  example: "order456"
                orderDescription:
                  type: string
                  description: Brief description of the order.
                  example: "Electronics Purchase"
                amount:
                  type: number
                  format: float
                  description: Total amount of the transaction.
                  example: 99.99
                quantity:
                  type: integer
                  description: Quantity of items in the order.
                  example: 2
                currency:
                  type: string
                  description: Currency code for the transaction.
                  example: "USD"
                transactionId:
                  type: string
                  description: Unique identifier for the transaction.
                  example: "txn789123"
                clientIP:
                  type: string
                  format: ipv4
                  description: IP address of the client.
                  example: "192.168.1.1"
                clientEmail:
                  type: string
                  format: email
                  description: Email address of the client.
                  example: "client@example.com"
                clientName:
                  type: string
                  description: Name of the client.
                  example: "John Doe"
                clientPhone:
                  type: string
                  description: Phone number of the client.
                  example: "+1234567890"
                paymentMethods:
                  type: string
                  description: Payment method used in the transaction.
                  example: "credit_card"
      responses:
        '200':
          description: Transaction processed successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - rquid
                  - statusCode
                  - statusMessage
                properties:
                  rquid:
                    type: string
                    format: uuid
                    description: Request unique identifier.
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  statusCode:
                    type: string
                    description: Status code of the response.
                    example: "200"
                  statusMessage:
                    type: string
                    description: Status message.
                    example: "OK"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    description: Status code of the response.
                    example: "400"
                  statusMessage:
                    type: string
                    description: Error message describing what went wrong.
                    example: "Bad Request"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    description: Status code of the response.
                    example: "500"
                  statusMessage:
                    type: string
                    description: Error message describing the server error.
                    example: "Internal Server Error"

components:
  schemas:
    TransactionRequest:
      type: object
      properties:
        rquid:
          type: string
          format: uuid
        datetime:
          type: string
          format: date-time
        returnUrl:
          type: string
          format: uri
        failUrl:
          type: string
          format: uri
        merchantid:
          type: string
        merchantName:
          type: string
        transactionType:
          type: string
          enum: [buy, cancel]
        orderid:
          type: string
        orderDescription:
          type: string
        amount:
          type: number
          format: float
        quantity:
          type: integer
        currency:
          type: string
        transactionId:
          type: string
        clientIP:
          type: string
          format: ipv4
        clientEmail:
          type: string
          format: email
        clientName:
          type: string
        clientPhone:
          type: string
        paymentMethods:
          type: string

    TransactionResponse:
      type: object
      properties:
        rquid:
          type: string
          format: uuid
        statusCode:
          type: string
        statusMessage:
          type: string