openapi: "3.0.0"
info:
  version: 1.0.0
  title: Purchase payment
  description: API for Purchase payment
  contact:
    name: Stella
    email: s.b.nagirner@gmail.com
servers:
  - url: http://api.example.com/hellostella/cancellpayment/api