openapi: "3.0.0"
info:
  version: 1.0.0
  title: Purchase payment
  description: API for Purchase payment
  contact:
    name: Stella
    email: s.b.nagirner@gmail.com
servers:
  - url: http://api.example.com/hellostella/fraudcheck/api

paths:
  /transaction:
    post:
      summary: Process a payment transaction
      operationId: processTransaction
      requestBody:
        description: JSON object containing payment transaction details for anti-fraud validation.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - rquid
                - datetime
                - transaction_id
                - dpan
                - order_id
                - merchant_id
                - merchant_name
                - transaction_type
                - amount
                - quantity
                - currency
                - client_email
                - client_name
                - payment_method
                - billing_address
              properties:
                rquid:
                  type: string
                  format: uuid
                  description: Unique identifier for the request.
                  example: "123e4567-e89b-12d3-a456-426614174000"
                datetime:
                  type: string
                  format: date-time
                  description: The date and time of the transaction request.
                  example: "2024-09-14T12:00:00Z"
                transaction_id:
                  type: string
                  description: Unique identifier for the transaction.
                  example: "txn789123"
                dpan:
                  type: string
                  description: The payment account number.
                  example: "1234AA6BB12345678"
                order_id:
                  type: string
                  description: Identifier for the order.
                  example: "order456"
                merchant_id:
                  type: string
                  description: Unique identifier for the merchant.
                  example: "merchant123"
                merchant_name:
                  type: string
                  description: Name of the merchant processing the transaction.
                  example: "Example Merchant"
                transaction_type:
                  type: string
                  enum: [buy, refund, cancel]
                  description: Type of transaction being processed.
                  example: "buy"
                amount:
                  type: number
                  format: float
                  description: Total amount of the transaction.
                  example: 99.99
                quantity:
                  type: integer
                  description: Quantity of items involved in the transaction.
                  example: 2
                currency:
                  type: string
                  description: Currency code for the transaction.
                  example: "usd"
                client_email:
                  type: string
                  format: email
                  description: Email address of the client.
                  example: "client@example.com"
                client_name:
                  type: string
                  description: Name of the client.
                  example: "John Doe"
                client_phone:
                  type: string
                  description: Phone number of the client.
                  example: "+1234567890"
                payment_method:
                  type: string
                  description: Method of payment used.
                  example: "credit_card"
                billing_address:
                  type: object
                  required:
                    - country
                    - city
                    - zip_code
                  properties:
                    country:
                      type: string
                      description: Country of the billing address.
                      example: "us"
                    city:
                      type: string
                      description: City of the billing address.
                      example: "New York"
                    zip_code:
                      type: string
                      description: Zip code of the billing address.
                      example: "10001"
      responses:
        '200':
          description: Transaction processed successfully with no issues detected.
          content:
            application/json:
              schema:
                type: object
                required:
                  - rquid
                  - statusCode
                  - statusMessage
                properties:
                  rquid:
                    type: string
                    format: uuid
                    description: Unique identifier for the request.
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  statusCode:
                    type: string
                    description: Status code of the response.
                    example: "200"
                  statusMessage:
                    type: string
                    description: Confirmation message for successful processing.
                    example: "OK"
        '400':
          description: Bad Request due to invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    description: Status code indicating a bad request.
                    example: "400"
                  statusMessage:
                    type: string
                    description: Error message explaining the bad request.
                    example: "Bad Request"
        '500':
          description: Internal Server Error indicating a server issue.
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    description: Status code indicating a server error.
                    example: "500"
                  statusMessage:
                    type: string
                    description: Error message describing the internal server issue.
                    example: "Internal Server Error"

components:
  schemas:
    TransactionRequest:
      type: object
      properties:
        rquid:
          type: string
          format: uuid
        datetime:
          type: string
          format: date-time
        transaction_id:
          type: string
        dpan:
          type: string
        order_id:
          type: string
        merchant_id:
          type: string
        merchant_name:
          type: string
        transaction_type:
          type: string
          enum: [buy, refund, cancel]
        amount:
          type: number
          format: float
        quantity:
          type: integer
        currency:
          type: string
        client_email:
          type: string
          format: email
        client_name:
          type: string
        client_phone:
          type: string
        payment_method:
          type: string
        billing_address:
          type: object
          properties:
            country:
              type: string
            city:
              type: string
            zip_code:
              type: string
            street_address:
              type: string

    TransactionResponse:
      type: object
      properties:
        rquid:
          type: string
          format: uuid
        statusCode:
          type: string
        statusMessage:
          type: string
